# Generated by Django 6.0 on 2025-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('workshop', 'Mental Health Workshop'), ('training', 'Employee Training Program'), ('consulting', 'Organizational Consulting'), ('wellbeing', 'Well-being Session')], max_length=50)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('preferred_date', models.DateField()),
                ('message', models.TextField(help_text='Describe your requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corporate Service Request',
                'verbose_name_plural': 'Corporate Service Requests',
            },
        ),
    ]
